spring:
  messages:
    basename: messages/messages
    fallback-to-system-locale: false
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/rrhh_evaluations
    username: adm-rrhh-evaluation
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: adm-rrhh-evaluation
      poolName: FwkCNAHikariCP
      minimumIdle: 2
      maximumPoolSize: 5
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      initializationFailTimeout: 0
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    schemas: adm-rrhh-evaluation
    user: adm-rrhh-evaluation
    password: admin
    locations: classpath:migration/versions
    baselineOnMigrate: true
    baselineVersion: 0

fwkcna:
  jpa:
    schema: adm-rrhh-evaluation
    data-migration:
      disabled: false
